include Makedefs.mingw32

.PHONY: all clean backup

all: Makefile
	$(MAKE) -f Makerules.mingw32 sueca.exe
clean:
	$(RM) $(OBJS) $(DEPS) *~ sueca.exe core core.[0-9]*

backup: PROJBASE="$(shell basename $(CURDIR))"
backup: clean
	cd ..; tar czf sueca-$(shell date '+%F-%H-%M').tar.gz $(PROJBASE)
