#ifndef _MYEVENTS_HPP_
#define _MYEVENTS_HPP_ 1

#include <wx/event.h>

BEGIN_DECLARE_EVENT_TYPES()
  DECLARE_LOCAL_EVENT_TYPE( CARD_MOVE_EVT_TYPE, 0 )
  DECLARE_LOCAL_EVENT_TYPE( CHAT_PANEL_MESSAGE_TYPE, 1 )
  DECLARE_LOCAL_EVENT_TYPE( FINISH_REMOTE_HANDLER_TYPE, 2 )
END_DECLARE_EVENT_TYPES()

#endif // _MYEVENTS_HPP_
